services:
  enroll_api:
    container_name: enroll_api
    build:
      context: .
      dockerfile: src/enroll_api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/enroll_api:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin}
      - MONGO_HOST=enroll_api_mongo
      - MONGO_PORT=27017
      - MONGO_DB=enroll_api

  mongo:
    container_name: enroll_api_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin} 
