services:
  enroll_api:
    container_name: enroll_api
    build:
      context: .
      dockerfile: src/enroll_api/Dockerfile
    ports:
      - "${ENROLL_API_PORT:-8000}:8000"
    volumes:
      - ./src/enroll_api:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      # MongoDB sem autenticação para desenvolvimento
      - MONGO_HOST=${MONGO_HOST:-enroll_api_mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DB=${MONGO_DB:-enroll_api}
      # RabbitMQ sem autenticação para desenvolvimento
      - RABBITMQ_HOST=${RABBITMQ_HOST:-enroll_api_rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE:-enrollment_queue}
      # Basic Auth Configuration
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-admin}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD:-secret123}
      - BASIC_AUTH_USERS=${BASIC_AUTH_USERS:-admin:secret123,config:config123}
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    container_name: enroll_api_mongo
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    # Removido autenticação para desenvolvimento
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin}

  rabbitmq:
    image: rabbitmq:3-management
    container_name: enroll_api_rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    # Removido autenticação para desenvolvimento
    # environment:
    #   RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
    #   RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}

  worker:
    build:
      context: ./src/worker
      dockerfile: Dockerfile
    volumes:
      - ./src/worker:/app
    container_name: enroll_api_worker
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST:-enroll_api_rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE:-enrollment_queue}
      # MongoDB sem autenticação para desenvolvimento
      - MONGO_URI=mongodb://enroll_api_mongo:${MONGO_PORT:-27017}/
      - MONGO_DB=${MONGO_DB:-enroll_api}
    depends_on:
      - mongo
      - rabbitmq
    restart: always